### ISSUE TITLE
Install Noticed 1.6 gem and generate sample notification

### ISSUE THREAD

**Issue by srb-** [pJeyakumar/noticed_upgrade_project#1]
In this ticket we will complete the following:
- install the noticed gem

**Comment by pJeyakumar** [comment]
Currently @srb- is creating a PR which installs noticed 1.6 to the Flight SIm App
- @hvillero and I will work on creating the mailers and notifications for the other models/controllers
- @srb- will work on #5 and create a test plan (and test cases using RSpec for the notifications)
