### ISSUE TITLE
Implement Noticed 1.6 and create tests for validation

### ISSUE THREAD

**Issue by srb-** [pJeyakumar/noticed_upgrade_project#2]
The purpose of this ticket is to familiarize ourselves with the noticed gem (particularly setting it up and running scaffolding commands to generate basic classes for the notifications).

**Comment by jonathanloos** [comment]
@srb- some base classes for initial implementation:

### application_notification.rb
```ruby
class ApplicationNotification < Noticed::Base
end
```

### application_mailer
- `has_history` will be introduced in #12 
```ruby
class ApplicationMailer < ActionMailer::Base
  default from: "SOME USER <email_here@example.com>"

  # ahoy::message tracker (not required off first setup)
  has_history extra: {sent: true}
end
```
