### ISSUE TITLE
Create upgrade guide/strategy based on this project's experiences

### ISSUE THREAD

**Issue by srb-** [pJeyakumar/noticed_upgrade_project#4]
Will garner inspiration from the [Noticed Update guide](https://github.com/excid3/noticed/blob/main/UPGRADE.md#noticed-20)
This issue #6 should also be worked on in tandem.

Changes to be made:
- Delete the `Notification` model in `app/models/notification.rb`.
  - Noticed v2 adds models managed by the gem.
- Change all instances of `deliver` to `deliver_later`.
  - Notifications are now always delivered later (meaning both of the above methods do the same thing), but we should change it to `deliver_later` for better clarity.
- Change all instances of `param` and `params` in the `Notifier` classes to `required_param` and `required_params` respectively.
- Wrap all helper methods in the `Notifier` classes with a new block `notification_methods do … end`
- Change all instances of `mark_as_read!` to `mark_as_read` and `mark_as_unread!` to `mark_as_unread`.
- Change all instances of `Noticed::Base`: to `Noticed::Event`.
- Remove all instances of `deliver_by :database` from notifiers.
  - The database delivery is now baked into notifications.
- Rename all `Notification` classes to be `Notifier` instead (this also means changing it from `app/notifications` to `app/notifiers`.
- `Has_noticed_notifications` changes described [here](https://github.com/excid3/noticed/blob/main/UPGRADE.md#has-noticed-notifications)
  - switching `has_noticed_notifications` in models to a `has_many` association instead.
- To migrate the data into new tables:
  - Create a variety of Notifications (4-5 for each type of Notification)
  - Create a `rake` task to loop through all existing notifications and create a new record for each one.
```ruby
# Temporarily define the Notification model to access the old table 
class Notification < ActiveRecord::Base 
  self.inheritance_column = nil 
end 
# Migrate each record to the new tables  
Notification.find_each do |notification|  
  attributes = notification.attributes.slice("type", "created_at", "updated_at").with_indifferent_access 
  attributes[:type] = attributes[:type].sub("Notification", "Notifier") 
  attributes[:params] = Noticed::Coder.load(notification.params) 
  attributes[:params] = {} if attributes[:params].try(:has_key?, "noticed_error") # Skip invalid records 
  # Extract related record to `belongs_to :record` association 
  # This allows ActiveRecord associations instead of querying the JSON data 
  # attributes[:record] = attributes[:params].delete(:user) || attributes[:params].delete(:account) 
  attributes[:notifications_attributes] = [{ 
    type: "#{attributes[:type]}::Notification",
    recipient_type: notification.recipient_type, 
    recipient_id: notification.recipient_id, 
    read_at: notification.read_at, 
    seen_at: notification.read_at, 
    created_at: notification.created_at, 
    updated_at: notification.updated_at 
  }] 
  Noticed::Event.create!(attributes) 
end
```
  - After migration and verifying that notifications work as intended and that all existing notifications are still present, we can drop the old notifications table.
- Need to run a migration to update the `type` column in all notifications: change all instances of `Notification` to `Notifier`.
```ruby
Noticed::Notification.find_each do |notification|
  notification.update(type: notification.type.sub("Notification", "Notifier"))
end
```

**Comment by jonathanloos** [comment]
Hey folks! So here is an example of a notification system and how it should be structured for this project.

### Usage
```ruby
# notifications
gem "noticed", "~> 1.6.0"
```

### Directory structure
```
app
> notifications
  > new_aircraft_created_notification.rb
> mailers
  > aircraft_mailer.rb
> views
  > aircraft_mailer
    > created_email.html.erb
```

### Invocation
```ruby
NewAircraftCreatedNotification.with(aircraft: aircraft).deliver_later(NewAircraftCreatedNotification.targets)
```

### Notification Class
```ruby
class NewAircraftCreatedNotification < ApplicationNotification
  deliver_by :database, if: :database_notifications?
  deliver_by :email, mailer: "AircraftMailer", method: "created_email", if: :email_notifications?

  # Variables that tells the system if it should send a notification if the recipient isn't subscribed
  DEFAULT_SEND_NOTIFICATION = true
  DEFAULT_SEND_EMAIL_NOTIFICATION = true

  # Add required params
  param :aircraft

  def message
    "#{params[:aircraft].name} has been created for use in the flight sim."
  end

  def url
    aircraft_path(params[:aircraft])
  end

  def database_notifications?
    DEFAULT_SEND_NOTIFICATION
  end

  def email_notifications?
    DEFAULT_SEND_EMAIL_NOTIFICATION
  end

  def self.targets
    # example of only sending notifications to admins. Really this just has to be an ActiveRecord::Relation of (likely) User objects.
    User.admin
  end
end
```

### Mailer
- Email tracking and click tracking will be completed in #12 
```ruby
class AircraftMailer < NotificationMailer
  before_action :set_user
  before_action :set_aircraft

  # use ahoy_messages to track all emails sent and track if their links are clicked.
  # this isn't necessary off the start and can be implemented after the fact in the above linked issue.
  track_clicks campaign: "aircraft_created_email", only: %i[created_email]

  has_history extra: -> { {sent: true, messageable: @aircraft} }

  def created_email
    mail(to: @user.email, subject: "[DIGITAL FLIGHT SIM] New Aircraft Created: #{@aircraft.name}")
  end

  private

  def set_user
    @user = params[:recipient]
  end

  def set_aircraft
    @aircraft = params[:aircraft]
  end
end
```

### User Model
```ruby
class User < ApplicationRecord
  has_many :notifications, as: :recipient, dependent: :destroy

  # Helper for associating and destroying Notification records where(params: {object: self}).
  has_noticed_notifications
  has_noticed_notifications param_name: :assigned_to, destroy: false, model_name: "Notification"
  has_noticed_notifications param_name: :requester, destroy: false, model_name: "Notification"
  has_noticed_notifications param_name: :granted_by, destroy: false, model_name: "Notification"
end
```

### Email Templates
```erb
<%# views/aircrafts_mailer/created_email %>

<p>Hello <%= @user.full_name %>,</p>
<br/>

<p>Aircraft <%= @aircraft %> has been created in the flight simulator.</p>
<br/>

<%= link_to "Check it out here", aircraft_url(@aircraft) %>
```

### Email testing
We use [letter_opener](https://github.com/ryanb/letter_opener) to preview emails locally.

**Comment by pJeyakumar** [comment]
@jonathanloos are we required to make any snapshots of the DB before we run the migrations? How are our DB backups structured (on Hanger).

**Comment by jonathanloos** [comment]
Yup our app's db is backed up with snapshots so there's no need to worry about us doing them. However, a rollback strategy without the backups (if possible) would be good to consider.

**Comment by srb-** [comment]
Looks good - assuming we make sure we update this doc with any snags/workarounds we hit when actually do https://github.com/pJeyakumar/noticed_upgrade_project/issues/3

@jonathanloos Are you using the AWS Aurora snapshots (every 5 minutes?), out of curiosity? Or what's the frequency of backup? Also, when's the last time you tested restoring from a backup, just wondering?

@pJeyakumar will the rake migration task cause downtime? How long would we expect it to last - I guess staging/dev will allow us to test realistically?

How will we validate we haven't lost any notifications in the process, on prod? Making sure row counts match?

**Comment by pJeyakumar** [comment]
@srb- the rake migration shouldn't cause any downtime given that we do our work in 2 distinct tasks.
1. Run the migration to create the new records for notifications (and we can also make sure that the `type` value of these notifications are changed from `Notification` to `Notifier`) in our first deployment.
- We would want to ensure that the app can work with both the new notifications table and old notifications table. 
2. After confirming that the app works with the new notifications table, we will run another deployment to clean up the codebase with anything that is no longer needed and drop the old notifications table.
Doing so should result in no downtime whilst we are changing the notifications in the DB.

To answer your second question:
It's hard to say exactly how long the rake migration will last (given that there are approx 1.5mil notifications, which hopefully will get trimmed down when we clean up unnecessary/ancient notifications). Though the Dev/Staging environments will give us an accurate stage of how the tests/migrations will work on Prod as well.

**Comment by srb-** [comment]
@pJeyakumar awesome, no downtime. Is there any concern with a notification being created in the old table while the migration is going on, and it gets missed? (e.g. any table locking, or after hours deployment, needed?) 

You mentioned the app will support both old and new Notifications at the same time. How will we toggle that? Feature flag (do we use those?) or through a new deployment?

**Comment by jonathanloos** [comment]
> Looks good - assuming we make sure we update this doc with any snags/workarounds we hit when actually do #3
> 
> @jonathanloos Are you using the AWS Aurora snapshots (every 5 minutes?), out of curiosity? Or what's the frequency of backup? Also, when's the last time you tested restoring from a backup, just wondering?
> 
> @pJeyakumar will the rake migration task cause downtime? How long would we expect it to last - I guess staging/dev will allow us to test realistically?
> 
> How will we validate we haven't lost any notifications in the process, on prod? Making sure row counts match?

@srb- we haven't done a formal restoration in a long time, but the staging restoration is very similar to what we would do. I would need to connect with our AWS resource to check the procedure. As for the frequency I would also need to confirm that! (sorry not much answers).

**Comment by hvillero** [comment]
@jonathanloos , For this upgrade, I understand that we may want to avoid downtime. However, considering a potential rollback situation, is there a good time during the day when we could run the upgrade if downtime becomes necessary? Additionally, knowing how long it would take to restore the previous database will help us estimate the required window of time.

**Comment by pJeyakumar** [comment]
> [@pJeyakumar](https://github.com/pJeyakumar) awesome, no downtime. Is there any concern with a notification being created in the old table while the migration is going on, and it gets missed? (e.g. any table locking, or after hours deployment, needed?)
> 
> You mentioned the app will support both old and new Notifications at the same time. How will we toggle that? Feature flag (do we use those?) or through a new deployment?

With migrations of this size, we typically have a button (in our Developer settings page, which is on the app) to run the rake file in batches.
- essentially the rake file would have an up-to-date list of all notifications, and then we'd go through that list in batches and create new records of each notification.
- we could also introduce a new column for the old notifications table (e.g. `new_notification_created`, which we would set to `true` once that notification's "new counterpart" has been created). We could use that `new_notification_created` column to keep track of all notifications which don't have a "new counterpart" (which will help ensure that no notifications are missed).

As for how the app will support both old and new notifications at the same time, we do not have Feature flags on the app, meaning we'd do it through a new deployment (my thinking is that our codebase should be able to support both the old/new notifications, if there is a noticeable difference between how we would handle both variations).

**Comment by jonathanloos** [comment]
@pJeyakumar all looks good here, but it's important to note here that the tasks will not be run as a migration. Rather, it will execute as a job we trigger manually. This has a couple benefits:
1. Should the migration fail (incorrect/timeout) the application will continue to run.
2. We can re-test migrations in staging after restorations daily.
3. We can chunk/batch the updates if needed.

For testing the migrations, remember we're dealing with over a million records. So for the rake task here we would want to have an idea of how long it will need to run for to pull & create all new records.
