### ISSUE TITLE
Create notification unit-test suite in preparation for upgrade validation

### ISSUE THREAD

**Issue by srb-** [pJeyakumar/noticed_upgrade_project#5]
Create a testing plan for full validation that any changes have not adversely affected Hangar.

We will need to include the [rspec-rails](https://rubygems.org/gems/rspec-rails/versions/6.0.3?locale=en) gem to create RSpec tests for the notification and mailer classes.
- These tests will determine if the corresponding notifications/emails are sent after a specific action and to the correct user.

**Comment by pJeyakumar** [comment]
[FactoryBot](https://github.com/thoughtbot/factory_bot) is used to create the factories for the RSpec tests.
