### ISSUE TITLE
Finish up Digital Flight Sim 3.0 base app

### ISSUE THREAD

**Issue by pJeyakumar** [pJeyakumar/noticed_upgrade_project#7]
- Finish:
  - linking the models together
  - setting up bootstrap
  - the overall user flow of the application

The above tasks can be easily done by following the commit history of this [github repo ](https://github.com/pJeyakumar/digitalaf_flight_sim).

**Comment by jonathanloos** [comment]
This doesn't include introduction of Noticed 1.6.
